from flask import Blueprint, request

from app.db import get_connection
from app.utils.responses import success_response, error_response
from app.utils.workout_planner import generate_workout_plan

workout_plan_bp = Blueprint("workout_plan", __name__)


@workout_plan_bp.route("/api/users/<int:user_id>/workout-plan", methods=["POST"])
def create_workout_plan(user_id):
    """
    Generate a personalized weekly workout plan based on the user's stored profile.

    If an AI provider is configured (the ANTHROPIC_API_KEY environment
    variable is set), the plan is generated by the AI. Otherwise -- or if
    the AI call fails for any reason -- a clearly-labeled, rule-based
    sample plan is returned instead, so this endpoint never just fails.

    No request body is required; the plan is based on the stored profile.
    """
    options = request.get_json(silent=True) or {}
    try:
        duration_minutes = int(options.get("duration_minutes", 30))
    except (TypeError, ValueError):
        return error_response("Choose a workout duration of 20, 30, or 45 minutes.", 400)
    equipment = options.get("equipment", "bodyweight")
    if duration_minutes not in (20, 30, 45):
        return error_response("Choose a workout duration of 20, 30, or 45 minutes.", 400)
    if equipment not in ("bodyweight", "home", "gym"):
        return error_response("Choose bodyweight, home equipment, or gym equipment.", 400)

    conn = get_connection()
    try:
        user_row = conn.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
    finally:
        conn.close()

    if not user_row:
        return error_response(f"User with id {user_id} not found.", 404)

    plan, source = generate_workout_plan(user_row, duration_minutes, equipment)

    return success_response(
        {
            "user_id": user_row["id"],
            "source": source,  # "ai" or "sample"
            "is_ai_generated": source == "ai",
            "plan": plan,
        }
    )
